name: macOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up vcpkg (Instala raylib/raygui)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
          vcpkgCache: true

      - name: Configure CMake
        uses: lukka/run-cmake@v10
        with:
          buildDirectory: '${{ github.workspace }}/build'
          cmakeOptions: '-DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release'

      - name: Build Project
        uses: lukka/run-cmake@v10
        with:
          buildDirectory: '${{ github.workspace }}/build'
          cmakeBuildTarget: 'all'
          cmakeBuildOptions: '--config Release'